# File: azure-pipelines\pull-request-validation\pr-msal.yml
# Description: Assemble and run unit test
# Variable: 'ENV_VSTS_MVN_ANDROIDADACCOUNTS_USERNAME' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
name: $(date:yyyyMMdd)$(rev:.r)

variables:
- name: BuildParameters.jdkVersion
  value: 1.8
- name: BuildParameters.jdkArchitecture
  value: x64
- name: BuildParameters.javaHomeSelection
  value: JDKVersion
- name: robolectricSdkVersion
  value: 28

trigger:
  branches:
    include:
    - dev
    - master
    - release/*
  batch: True

resources:
  repositories:
  - repository: common
    type: github
    name: AzureAD/microsoft-authentication-library-common-for-android
    ref: dev
    endpoint: ANDROID_GITHUB

jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: azure-pipelines/templates/steps/credscan-policheck.yml@common
    parameters:
      policheckCmdLineArgsDir: msal
  - template: azure-pipelines/templates/steps/automation-cert.yml@common
  - task: JavaToolInstaller@0
    displayName: Use Java 8
    inputs:
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: Gradle@2
    name: Gradle1
    displayName: Assemble Release
    inputs:
      tasks: clean msal:assembleLocal
      publishJUnitResults: false
      testResultsFiles: '**/build/test-results/TEST-*.xml'
      jdkVersion: $(BuildParameters.jdkVersion)
      jdkArchitecture: $(BuildParameters.jdkArchitecture)
      sqGradlePluginVersion: 2.0.1
  - task: Gradle@2
    displayName: Run Unit tests
    inputs:
      tasks: msal:testLocalDebugUnitTest -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}}
      javaHomeSelection: $(BuildParameters.javaHomeSelection)
      jdkVersion: 1.11
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection
...
